<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Autenticacao\Commands\" />
    <Folder Include="Autenticacao\Interfaces\" />
    <Folder Include="Autenticacao\UseCases\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\APICasamento.Domain\APICasamento.Domain.csproj" />
  </ItemGroup>

</Project>
